title: LASTQ
description: An explanation of the platform-agnostic "standard" linked-read data format
theme: just-the-docs

url: https://pdimens.github.io/lastq

aux_links:
  LASTQ Github: https://github.com/pdimens/lastq
