base_url = "https://pdimens.github.io/lastq/"
title = "Standard Linked-Read Format"
theme = "tanuki"
build_search_index = true


[extra]
mode = "docs"
github = "https://github.com/pdimens/lastq"
favicon = "/img/logo.png"